In [1]:
import pandas as pd
import numpy as np

In [52]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Lasso, Ridge, LinearRegression

### Выгрузим и подготовим данные

In [84]:
train = pd.read_csv('train.csv')

In [85]:
test = pd.read_csv('test.csv')

In [86]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15129 entries, 0 to 15128
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             15129 non-null  int64  
 1   date           15129 non-null  object 
 2   price          13763 non-null  float64
 3   bedrooms       13615 non-null  float64
 4   bathrooms      13616 non-null  float64
 5   sqft_living    13618 non-null  float64
 6   sqft_lot       13618 non-null  float64
 7   floors         14683 non-null  float64
 8   waterfront     14677 non-null  float64
 9   view           14695 non-null  float64
 10  condition      14656 non-null  float64
 11  grade          14666 non-null  float64
 12  sqft_above     13569 non-null  float64
 13  sqft_basement  14662 non-null  float64
 14  yr_built       14679 non-null  float64
 15  yr_renovated   14677 non-null  float64
 16  zipcode        14692 non-null  float64
 17  lat            14682 non-null  float64
 18  long  

In [87]:
train = train.dropna(subset=['price'])

In [88]:
train = train.fillna(train.median())

In [89]:
train.drop(['id', 'date'], axis=1, inplace=True)
X = train.drop("price",axis=1).values
y = train["price"].values

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=3)

### Приведем данные к одному масштабу

In [91]:
scaler = StandardScaler()

In [92]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

### Обучим на кросвалидации

In [93]:
cross_val_score(LinearRegression(), X_train, y_train, cv=5, scoring='r2')

array([0.11094597, 0.09988982, 0.0926483 , 0.13329151, 0.09695979])

In [94]:
cross_val_score(Ridge(), X_train, y_train, cv=5, scoring='r2')

array([0.11094675, 0.0998904 , 0.09265101, 0.1332955 , 0.09696372])

In [95]:
cross_val_score(Ridge(), X_train, y_train, cv=5, scoring='r2')

array([0.11094675, 0.0998904 , 0.09265101, 0.1332955 , 0.09696372])

In [96]:
lr = LinearRegression()
lr.fit(X_train, y_train)
print(r2_score(y_test, lr.predict(X_test)))

0.12801444190135158


In [97]:
print(r2_score(y_out, np.ones(y_out.shape) * y_train.mean()))

-6.734133595931446e-05


### Проверим качество на тесте

In [98]:
test = test.dropna(subset=['price'])
test = test.fillna(train.median())

In [99]:
test.drop(['id', 'date'], axis=1, inplace=True)
X_out = test.drop("price",axis=1).values
y_out = test["price"].values

In [100]:
X_out = scaler.transform(X_out)

In [101]:
print(r2_score(y_out, lr.predict(X_out)))

0.10680749761200925


In [102]:
print(r2_score(y_out, np.ones(y_out.shape) * y_train.mean()))

-6.734133595931446e-05
